name: Deploy to Docker Hub

on:
  workflow_run:
    workflows: ["Test Workflow"]  # Replace with the name of your test workflow
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t yourusername/yourrepository:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: docker push yourusername/yourrepository:${{ github.sha }}
