name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t yourusername/yourappname:${{ github.sha }} .
          docker push yourusername/yourappname:${{ github.sha }}

      - name: Clean up post-build
        run: docker rmi yourusername/yourappname:${{ github.sha }}
