name: Deploy Workflow

on:
  workflow_run:
    workflows: ["Test Workflow"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Your Docker Hub username
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t yourusername/yourrepository:${{ github.sha }} .
        docker push yourusername/yourrepository:${{ github.sha }}
