name: Test Workflow

on:
  push:
    branches:
      - main

jobs:
  check-for-test-script:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    outputs:
      tests-present: ${{ steps.check-tests.outputs.tests-present }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working directory
        run: pwd
      
      - name: Check for test script
        id: check-tests
        shell: bash
        run: |
          if [ -f /home/runner/work/SegmentacijaSlik/SegmentacijaSlik/test.py ]; then
            echo "Test script found."
            echo "tests-present=true" >> $GITHUB_ENV
          else
            echo "Test script not found." >&2
            exit 1
          fi


  run-tests:
    needs: check-for-test-script
    if: ${{ needs.check-for-test-script.outputs.tests-present == 'true' }}
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']  # Define a matrix for Python versions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install numpy opencv-python

      - name: Run tests
        run: python test.py
